### ISSUE TITLE
`fatal error: concurrent map writes' when uploading to SFTP

### ISSUE THREAD

**Issue by wadujj** [pkg/sftp#135]
I have encountered the following error. I am on Go 1.6.2

Looking at the code it seems [https://github.com/pkg/sftp/blob/master/conn.go#L32](https://github.com/pkg/sftp/blob/master/conn.go#L32)  should have protected this. However at the time on panic, the following trace is generated by 2 goroutines in this package.  

[https://github.com/pkg/sftp/blob/master/conn.go#L795](https://github.com/pkg/sftp/blob/master/conn.go#L95)

```
fatal error: concurrent map writes
goroutine 1 [running]:
runtime.throw(0x8df830, 0x15)
	/.BUILD/go/src/runtime/panic.go:547 +0x90 fp=0xc8204f91b0 sp=0xc8204f9198
runtime.mapassign1(0x7548c0, 0xc8200fe8d0, 0xc8204f9284, 0xc8204f9288)
	/.BUILD/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc8204f9258 sp=0xc8204f91b0
gorpt/vendor/github.com/pkg/sftp.(*clientConn).dispatchRequest(0xc82001d1a0, 0xc8202d2300, 0x7f74dc258100, 0xc82064a300)
	/.BUILD/go-work/src/gorpt/vendor/github.com/pkg/sftp/conn.go:95 +0x9c fp=0xc8204f92d8 sp=0xc8204f9258
gorpt/vendor/github.com/pkg/sftp.(*File).ReadFrom(0xc8200ffb00, 0x7f74dc257b68, 0xc8200143f0, 0xc8204f9508, 0x0, 0x0)
	/.BUILD/go-work/src/gorpt/vendor/github.com/pkg/sftp/client.go:970 +0x333 fp=0xc8204f9488 sp=0xc8204f92d8
io.copyBuffer(0x7f74dc257b40, 0xc8200ffb00, 0x7f74dc257b68, 0xc8200143f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/.BUILD/go/src/io/io.go:374 +0x180 fp=0xc8204f9548 sp=0xc8204f9488
io.Copy(0x7f74dc257b40, 0xc8200ffb00, 0x7f74dc257b68, 0xc8200143f0, 0xc8200143f0, 0x0, 0x0)
	/.BUILD/go/src/io/io.go:350 +0x64 fp=0xc8204f95a0 sp=0xc8204f9548
gorpt/merger.MergeSrcToTarget(0x7ffde5d618c6, 0x13, 0x7ffde5d61918, 0x16, 0x7ffde5d6193c, 0x12, 0xc8204a8730, 0x5, 0xc8, 0x7f74dc256988, ...)
...
...
	/.BUILD/go-work/src/gorpt/merger/main/main.go:101 +0x10aa fp=0xc8204f9f40 sp=0xc8204f9c60
runtime.main()
	/.BUILD/go/src/runtime/proc.go:188 +0x2b0 fp=0xc8204f9f90 sp=0xc8204f9f40
runtime.goexit()
	/.BUILD/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8204f9f98 sp=0xc8204f9f90
```
and 

[https://github.com/pkg/sftp/blob/master/conn.go#L70](https://github.com/pkg/sftp/blob/master/conn.go#L70)

```
goroutine 78 [chan send]:
gorpt/vendor/github.com/pkg/sftp.(*clientConn).recv(0xc82001d140, 0x0, 0x0)
	/.BUILD/go-work/src/gorpt/vendor/github.com/pkg/sftp/conn.go:70 +0x461
gorpt/vendor/github.com/pkg/sftp.(*clientConn).loop(0xc82001d140)
	/.BUILD/go-work/src/gorpt/vendor/github.com/pkg/sftp/conn.go:44 +0x5a
created by gorpt/vendor/github.com/pkg/sftp.NewClientPipe
	/.BUILD/go-work/src/gorpt/vendor/github.com/pkg/sftp/client.go:77 +0x2c1
```

**Comment by wadujj** [comment]
The issue was in the way I was creating the SFTP client in my code.
