### ISSUE TITLE
fuzzer crash report

### ISSUE THREAD

**Issue by drakkan** [pkg/sftp#418]
Hi,

the fuzzer reported another crash, here is the stack trace:

```
goroutine 21 [running]:
github.com/pkg/sftp.unmarshalUint32(...)
 github.com/pkg/sftp/packet.go:75
github.com/pkg/sftp.(*clientConn).recv(0x10c0000ce090, 0x0, 0x0)
 github.com/pkg/sftp/conn.go:87 +0x2bc
github.com/pkg/sftp.(*clientConn).loop(0x10c0000ce090)
 github.com/pkg/sftp/conn.go:71 +0x69
created by github.com/pkg/sftp.NewClientPipe
 github.com/pkg/sftp/client.go:237 +0x32b
==176339== ERROR: libFuzzer: deadly signal
    #0 0x52bb91 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:86:3
    #1 0x4748e8 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x4584c3 in fuzzer::Fuzzer::CrashCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233:3
    #3 0x7f755a87138f in libpthread.so.0
    #4 0x5bf500 in runtime.raise runtime/sys_linux_amd64.s:163
```

it should be easy to fix as #411 but I'm unable to provide a patch for the next few weeks, sorry

**Comment by puellanivis** [comment]
Indeed, looks like there is another “unsafe” read: https://github.com/pkg/sftp/blob/e164c76a1254f2d3e747327c7c7a061a1f7539f2/conn.go#L87
